version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs 
      - ./vhost:/etc/nginx/vhost.d 
      - ./html:/usr/share/nginx/html
    restart: always
    privileged: true
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    environment:
        - DEFAULT_EMAIL=aarenchu@gmail.com
  frontend:
    image: projectfrontend:latest
    build: 
      context: ./frontend
      args:
        REACT_APP_API_URL: https://api.covid19vaxtracker.live
    container_name: projectfrontend
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: www.covid19vaxtracker.live
      LETSENCRYPT_HOST: www.covid19vaxtracker.live
  backend:
    image: projectbackend:latest
    build: ./backend
    container_name: projectbackend
    restart: always
    expose:
      - 3000
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: CEZHrExc5aMCcp5s
      MONGO_DB: VaccDataDev
      VIRTUAL_HOST: api.covid19vaxtracker.live
      LETSENCRYPT_HOST: api.covid19vaxtracker.live