version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=mohamedntayeh@gmail.com

  frontend:
    image: ghcr.io/UTSCC09/frontendcovid19vaxtracker
    container_name: frontendcovid19vaxtracker
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=covid19vaxtracker.live
      - LETSENCRYPT_HOST=covid19vaxtracker.live

  backend:
    image: ghcr.io/UTSCC09/backendcovid19vaxtracker
    container_name: backendcovid19vaxtracker
    restart: always
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=api.covid19vaxtracker.live
      - LETSENCRYPT_HOST=api.covid19vaxtracker.live
