name: Build and Deploy Website

on:
  push:
    # Only run this workflow if it is a commit to main.
    branches:
      - main
    # Only run this workflow if the commit has modified files from any of frontend, backend, or docker-compose.yml
    paths:
      - 'docker-compose.yml'
      - frontend/**
      - backend/**
  # From https://stevenmortimer.com/running-github-actions-sequentially/
  # repository_dispatch:
  #   branches:
  #     - main
  #   types: [trigger-deploy-workflow]

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    defaults:
      run:
        working-directory: .

    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        # Checks for changes in files
        - uses: dorny/paths-filter@v2
          id: changes
          with:
              filters: |
                backend:
                  - 'backend/**'
                frontend:
                  - 'frontend/**'
                docker-compose:
                  - 'docker-compose.yml'
        - name: Copy over new docker-compose.yml if changed
          if: steps.changes.outputs.docker-compose == 'true'
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            source: "docker-compose.yml"
            target: "~"
        - name: Copy over backend/ if changed
          if: steps.changes.outputs.backend == 'true'
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            source: "backend/"
            target: "~"
        - name: Copy over frontend/ if changed
          if: steps.changes.outputs.frontend == 'true'
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            source: "frontend/"
            target: "~"
        - name: Build frontend when necessary
          if: steps.changes.outputs.frontend == 'true'
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            script: |
              docker-compose build frontend
        - name: Build backend when necessary
          if: steps.changes.outputs.backend == 'true'
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            script: |
              docker-compose build backend
        - name: Deploy in Container
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            script: |
              docker-compose up -d