name: Deploy Website

on:
  push:
    # Only run this workflow if it is a commit to main.
    branches:
      - main
    # Only run this workflow if the commit has modified files from any of frontend, backend, or docker-compose.yml
    paths:
      - 'docker-compose.yml'
  # From https://stevenmortimer.com/running-github-actions-sequentially/
  repository_dispatch:
    branches:
      - main
    types: [trigger-deploy-workflow]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    defaults:
      run:
        working-directory: .

    steps:
        - name: Pull Images and Deploy in Container
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            script: |
              cd project
              docker-compose pull && docker-compose up -d