name: Deploy Website

on:
  push:
    # Only run this workflow if it is a commit to main.
    branches:
      - main
    # Only run this workflow if the commit has modified files from any of frontend, backend, or docker-compose.yml
    paths:
      - 'docker-compose.yml'
  # From https://stevenmortimer.com/running-github-actions-sequentially/
  repository_dispatch:
    branches:
      - main
    types: [trigger-deploy-workflow]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    defaults:
      run:
        working-directory: .

    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        # Runs a set of commands using the runners shell
        - name: Debug problem
          run: |
            ls
        - name: Copy over new docker-compose.yml
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            source: "docker-compose.yml"
            target: "~"
        - name: Pull Images and Deploy in Container
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            script: |
              echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
              docker-compose pull && docker-compose up -d
              docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' projectfrontend